### ISSUE TITLE
frame feature

### ISSUE THREAD

**Issue by KirillSerg** [KirillSerg/drawler#12]
add a frame for selecting an clicked element area

**Comment by roman01la** [comment]
I'm not sure I understand what this is doing. Can you please explain?

**Comment by KirillSerg** [comment]
> I'm not sure I understand what this is doing. Can you please explain?
it is about the frame around of element(block)
![image](https://github.com/KirillSerg/drawler/assets/99827460/d1a1400f-6848-48cb-b0e2-5e49332976d0)
